# Generated by Django 3.1 on 2021-05-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(help_text='Agent string', max_length=200, unique=True)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('is_bot', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-device'],
            },
        ),
        migrations.CreateModel(
            name='ExcludeHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Example: *googleapis.com', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to capture http requests')),
                ('http_requests', models.JSONField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='http_requests_viewer.agent')),
                ('exclude_hosts', models.ManyToManyField(blank=True, to='http_requests_viewer.ExcludeHost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
